### ISSUE TITLE
Undetected HEIC images are not converted to jpg images

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/UCLAbookstack#116]
**Describe the bug**
There exists a corner case that causes our backend to miss detection of HEIC files (which we need in order to convert them to jpg images). This results in uploading an HEIC image to our backend, and thus failing to convert said image to our 'optimized bucket'. As a result, on our website, the image never loads, and we get the following shown below.

You can see that the iClicker 2, never displays.
<img width="757" alt="Screen Shot 2020-10-31 at 3 51 23 AM" src="https://user-images.githubusercontent.com/25701682/97777281-5a27c980-1b2c-11eb-893f-47b5b8fbc9b4.png">

**To Reproduce**
1. Get an HEIC image
2. Rename the file to have a .jpg/.jpeg/.png extension (not converting it, but simply renaming, I renamed it to have a .jpg extension)
3. Make a new post with the undercover HEIC image
4. You'll see that the image never loads, and that is because our lambda function in AWS cannot optimize HEIC images.
5. Further, try to 'inspect element', and grab the url that the 'not loading undercover HEIC image' is trying to fetch it from.
      - Should be something like "**_https://ucla-bookstack-optimized-photos.s3-us-west-1.amazonaws.com/5f4df5a4e7f48001a880/images-159063219.JPG_**" or something like that.
6. Notice that by actually going to that link, AWS throws a 403 (forbidden) error. This isn't because of permissions, but because the image does not exist. the lambda function never optimized the uploaded image, because it Is incompatible with HEIC images.

**Expected behavior**
We want all HEIC images to be detected and converted to genuine .jpg images. 
In order to do this, we probably have to have a check in the backend, like we do on our frontend.
This would mean that rather than checking for '.heic' as an extension, going into the file and checking the first few bytes, and confirming that we have the correct/intended file type.
This method would result in a much more thorough inspection of the uploaded file, and save us from not detecting 'undercover HEIC images'

**Sidenote**

I found this bug when someone tried to upload a post to BookStack, and I have no idea how this 'lazyily just renaming the file' would happen naturally, because I had to manually rename the HEIC file in order to catch the error. I would hope that Apple would have that covered. Regardless, it happened, and we should account for it.

**Comment by ntjoar** [comment]
Solution should be to analyze our buffer. Will work on this solution and push as soon as possible
