### ISSUE TITLE
Add an 'edit' post form

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/UCLAbookstack#34]
**Is your feature request related to a problem? Please describe.**
When we create a post, we can only delete the post as of now. This is an issue if you only want to change one thing.

**Proposed Solution**
Next to the delete button, I would like to add an edit button just in case you just want to change one thing about the post but not necessarily delete it entirely.

**Comment by bryansimca20** [comment]
This feature might be important for deployment. Can we move this up to priority - high?
