### ISSUE TITLE
Possible bug in searching through db for books

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/UCLAbookstack#37]
**Describe the bug**
When we input a search term, it takes that term as a string, but say that a user input two words, Ideally we would want any string that had either one of those strings (or strings that contain both)?

However under the current implementation, it is possible that:

if we have 3 items, named:
1 words included in here only
2 words only out there
3. we use lots of words

and we search for, 'words' all 3 would pop up, but what if we search for 'words only'?

I have to check if this would return only 'words only out there' or if it will correctly return both 'words included in here only' and 'words only out there'

**Comment by jcr7467** [comment]
The fix to this would probably just ensuring that the parameter passed into Book.paginate({ ... }) is accurate, probably some sort of regex. This would be found in router.get('/search/:pagenumber') inside of routes/routes.js


Right now I just use the search term typed into the search box I believe. 
I haven't even tried this so I am not sure if this bug even exists yet.


I would suggest making two posts with the same words but in different order and looking at the results to see if my suspicions are correct.

**Comment by ntjoar** [comment]
The bug exists, currently searches for only exact matches. I propose splitting words by spaces and possibly searching per word rather than worry about working regex. Possibly sorting it all into a list and removing repeats?

**Comment by ntjoar** [comment]
Should be done. See ntjoar branch

**Comment by jcr7467** [comment]
Issue resolved. Closing
