### ISSUE TITLE
Make checkbox and “I agree w terms” css inline

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/UCLAbookstack#5]

**Comment by jcr7467** [comment]
This is the checkbox that is at the footer when a user is not logged in
Right now, the checkbox and the message or on different lines

**Comment by jcr7467** [comment]
<img width="428" alt="Screen Shot 2020-09-01 at 3 31 42 PM" src="https://user-images.githubusercontent.com/25701682/91912538-3e0cc680-ec68-11ea-91fa-868ae7964759.png">

**Comment by jcr7467** [comment]
This is located in the footer when a user is not logged in

**Comment by ntjoar** [comment]
Pushed inline code, need to refactor so inline commands are in proper files
