### ISSUE TITLE
Fix pagination

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/UCLAbookstack#50]
**Describe the bug**
Pagination is still not perfect. When we filter our results based on category and we only have one result, it glitches out and says:

" Showing - of 1 results."  In this case, it should say "Showing 1-1 of 1 results" because in other cases we would say "Showing 50-75 of 200 results"

**To Reproduce**
1. Search for all books
2. Filter them down with the left category bar until there is only one result
**Screenshots**

<img width="957" alt="Screen Shot 2020-10-01 at 2 09 40 AM" src="https://user-images.githubusercontent.com/25701682/94790516-3df90700-038b-11eb-8414-fb4a2cdd8b4f.png">

**Comment by jcr7467** [comment]
This means that those numbers passed in from the backend are null for some reason

**Comment by ntjoar** [comment]
So it looks like when we add any filter at all, the numbers aren't passing from backend
