### ISSUE TITLE
Remove space between "Hi !" in header when someone isn't logged in

### ISSUE THREAD

**Issue by NoahTarr** [jcr7467/UCLAbookstack#52]
**Describe the bug**
Remove space between "Hi !" in the header when someone isn't logged in

**Expected behavior**
It looks strange as it is. I'd recommend either removing the "Hi !" altogether when someone isn't logged in or at least removing the space. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11342043/94845190-314cd100-03d4-11eb-91d1-748b0e367bad.png)

**Comment by jcr7467** [comment]
I agree actually now that I think of it
