### ISSUE TITLE
New footer signup form styling is off compared to remainder of the website

### ISSUE THREAD

**Issue by NoahTarr** [jcr7467/UCLAbookstack#53]
**Describe the bug**
The styling for the checkbox and the submit button do not follow the styles for similar elements through the site. The submit button should have similar behavior to other buttons, such as the login button. The checkbox should also use a pointer cursor rather than default. 

**Expected behavior**
The formatting would look nicer if you put the checkbox directly to the left of the "I've read & agree..." statement rather than above.

**Screenshots**
![image](https://user-images.githubusercontent.com/11342043/94845901-36f6e680-03d5-11eb-8642-eeeff5025abb.png)
Not hovered: 
![image](https://user-images.githubusercontent.com/11342043/94846020-58f06900-03d5-11eb-8c59-80cd8e0eeff6.png)

Hovered: 
![image](https://user-images.githubusercontent.com/11342043/94846033-5beb5980-03d5-11eb-8be2-0a6a8ab225ec.png)

**Additional context**

**Comment by ntjoar** [comment]
See issue #5

**Comment by jcr7467** [comment]
I tried to change the style of this button, but in the current implementation, it is a <input> tag, while the other buttons on the page are of type <button class="btn btn-secondary swipe-to-top">. But when I replace it with a button tag, I get this down below

<img width="325" alt="Screen Shot 2020-10-04 at 12 10 30 PM" src="https://user-images.githubusercontent.com/25701682/95024863-9ace1900-063a-11eb-8ae2-9bca986ef914.png">


_Inside of views/partials/footers/default_footer.hbs_ I tried this
<img width="882" alt="Screen Shot 2020-10-04 at 12 12 56 PM" src="https://user-images.githubusercontent.com/25701682/95024931-f26c8480-063a-11eb-98d6-592dce466a00.png">

**Comment by NoahTarr** [comment]
FIxed styling for default footer:
![image](https://user-images.githubusercontent.com/11342043/95332672-9b47f900-0860-11eb-887c-d8ce4e2b1547.png)

Fixed styling for mobile footer:
![image](https://user-images.githubusercontent.com/11342043/95332762-b7e43100-0860-11eb-96fd-00a230cc0f79.png)
