### ISSUE TITLE
Sticky Navbar Broken

### ISSUE THREAD

**Issue by NoahTarr** [jcr7467/UCLAbookstack#62]
**Describe the bug**
Sticky Navbar when Scrolling is broken on the home screen.
It also is not working on the books page, but this may or may not be an issue.

**To Reproduce**
1. Go to home page
2. Scroll

**Expected behavior**
The sticky navbar should be a condensed version of the normal navbar. Still holding all elements like search bar etc..

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/11342043/95328612-a6982600-085a-11eb-9275-4b29a6eb16d4.png)

Expected:
![image](https://user-images.githubusercontent.com/11342043/95328541-8c5e4800-085a-11eb-8dee-737fe5b59316.png)

**Comment by jcr7467** [comment]
This is because of issue #40 , but generalized, there might be other interferences as well

**Comment by bryansimca20** [comment]
I think i fixed it along with issue #5
