### ISSUE TITLE
Make register page require two email fields to verify the user input the password they meant to input

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/UCLAbookstack#7]

**Comment by jcr7467** [comment]
When we create a new account, it only asks the user to input a password once. This will likely cause a user to accidentally enter the wrong password.

**Comment by jcr7467** [comment]
This task would only consist of creating a new front end element to verify, and on the backend making sure that the values of both fields are equal. If not, send an error. Or somehow verify on the front end if they are equal.

**Comment by jcr7467** [comment]
Keep in mind that we will have to add the changes to both the signup page, as well as the form located at the bottom footer when a user is not logged in

**Comment by ntjoar** [comment]
Confirm password text field has been added, but when trying to check, it keeps throwing an error. Looking into it

**Comment by ntjoar** [comment]
Password input id needed to be "password" for whatever reason

**Comment by ntjoar** [comment]
Changed to inlineFormInputGroup1 for prior script redundancy

**Comment by jcr7467** [comment]
Issue resolved
