### ISSUE TITLE
Bug page popped up upon clicking verify email

### ISSUE THREAD

**Issue by bryansimca20** [jcr7467/UCLAbookstack#97]
**Describe the bug**
This page popped up when I clicked the verify email on the profile page

**Screenshots**
![image](https://user-images.githubusercontent.com/64670861/96889585-96c43880-143b-11eb-816c-b7fbf0e76c98.png)

**Comment by jcr7467** [comment]
This is due to the non updated environmental variables on the deployed version. If this was ran on localhost, try replacing your .env file with the one I sent you

**Comment by jcr7467** [comment]
Just updated deployed environmental variables. Let me know if the issue still pops up. It should be good now.

I am going to leave this issue open for now until you confirm that it indeed works. Feel free to close this issue when/if everything looks good.

**Comment by bryansimca20** [comment]
Looks good now!
